### ISSUE TITLE
SystemUI has stopped

### ISSUE THREAD

**Issue by kientux** [MohammadAG/Xposed-Tinted-Status-Bar#43]
SystemUI has stopped everytime I install this, but only in one ROM. I realized that when TSB changes status bar color (when I switch between activity), SystemUI stops.Here's the SystemUI.apk, can you take a look? https://db.tt/w3xzFsxQ

If you want me to provide logs or something, please tell me.

**Comment by MohammadAG** [comment]
I need a log filtered for AndroidRuntime.

**Comment by kientux** [comment]
Sorry for late reply, it takes me 2 hours to enable logcat because the ROM's dev has disabled it :(

Here the logcat filtered for AndroidRuntime: http://pastebin.com/QpdCWf4j

**Comment by kientux** [comment]
I'm noob but after read the log, maybe the problem is navigation bar? I disabled navbar and systemui is no more stopped.

**Comment by asadkhan6** [comment]
@MohammadAG i am also facing this issue...
I am using on GT-N7100 4.4.2 stock rom
and it gives me an error "com.android.systemui" has stopped every time I try to answer or make a call, pulling my Pen out or playing music.
First i thought it was wanam Xposed error but i've uninstalled it and still got this error now i searched and found that i am not the only one who is facing this issue 
It is a great app 
PLEASE HELP...

**Comment by GermainZ** [comment]
@kientux this shouldn't happen anymore from what I can see, since the line that caused the crash is now wrapped in a try/catch block.

@asadkhan6 that says nothing (and it doesn't mean it's the same issue — the cause might be very different), you'll need to provide a logcat and open a new issue, assuming you're sure TSB is causing this (does it happen if all modules are disabled? if all modules except TSB are disabled? if you answered "yes" to the first, or "no" to the first and "yes" to the second, then it's probably TSB's fault).
