### ISSUE TITLE
Status bar icons not tinting

### ISSUE THREAD

**Issue by Avamander** [MohammadAG/Xposed-Tinted-Status-Bar#63]
Software: CM11 unofficial by Varcain. Xposed 2.6.1, TSB 1.8.9.3.
Bug: Status bar icons do not change their colors, even when different coloring mode or the color is manually set.

**Comment by LiquidPL** [comment]
Also confirming this on Paranoid Android 4.4.1, Xposed 2.6.1, TSB 1.8.9.3

**Comment by LiquidPL** [comment]
Alright i think i found the issue here. Statusbar icons don't change their colors when the 'Show a gradient over tint' option in 'appearence' category is enabled.

Off:
![screenshot_2014-07-10-23-09-31](https://cloud.githubusercontent.com/assets/991831/3545449/c99c7e52-0876-11e4-9492-a727a4aeefd1.png)

On:
![screenshot_2014-07-10-23-08-58](https://cloud.githubusercontent.com/assets/991831/3545448/c9994b92-0876-11e4-8eef-956a8cea2113.png)

**Comment by Bhediyaa** [comment]
and when gradient is active...the icons turns a bit off white throughout
and as i tick it off
they turn the actual kitkat white
touchwiz 4.4.2 tab 3

**Comment by Avamander** [comment]
I think if atleast black and white tinted icon support is added all is fine.

**Comment by GermainZ** [comment]
The following commits should fix these issues.

Clock: b2beb7944f44d874776131b6178063c3879add33 (already in 1.8.9.3)
Battery: 1437914e5452a7566cd2f3607b79160ffc12ba5f (will be in the next version)
White icons when the overlay is enabled: a7ec5bd76c4e5fd57aa4c0f92a96693ce07c0f28 (will be in the next version)

If you still encounter this issue once you get the next version (or compile manually), open another issue and mention the exact ROM you're using.
